version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - messageDB:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=message_db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes: 
      - messageRedis:/data

volumes:
  messageDB:
  messageRedis:

